---
title: "About"
---



This a one-day Hackathon with the goal to reproduce a social scientific paper as a group.

The event will take place on 24th July from 9:30-15:15 at the Edinburgh Futures Institute (EFI)

We are supported by the University of Edinburgh Research Training Centre (RTC).


## Motivation

There is an often-cited “reproducibility crisis” in the Social Sciences, where most published results go unverified. In response to these concerns, it is becoming more common for authors to make their code and data public. However, the code provided is often incomplete (e.g., does not include cleaning or recoding details) or is never tested by reviewers. Sometimes no code is provided at all, but there should be enough information in the methods section to rewrite the analysis.

We need time set aside for researchers to put existing articles to the test. The result will be to either add greater credibility to the claim (if the results match) or identify findings that need revisiting from the original authors (if results cannot be reproduced).
Undertaking reproducibility work in a team environment also presents a collaborative learning opportunity for statistical social scientists to discuss their interpretations of the papers, share coding knowledge, and discuss best practices as a research community.


## Outputs

Participants will collaboratively publish the resulting code and comparison with paper findings on this Quarto website.